### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by ssoftwares** [anastr/RulerView#3]
android.view.InflateException: Binary XML file line #192 in com.ssoftwares.dify:layout/fragment_courier: Binary XML file line #192 in com.ssoftwares.dify:layout/fragment_courier: Error inflating class com.github.anastr.rulerview.RulerView
    Caused by: android.view.InflateException: Binary XML file line #192 in com.ssoftwares.dify:layout/fragment_courier: Error inflating class com.github.anastr.rulerview.RulerView
    Caused by: java.lang.reflect.InvocationTargetException

**Comment by anastr** [comment]
this is not the Exception, please send the full log and xml file

**Comment by ssoftwares** [comment]
It is an exception sir, i just put your xml code into my xml and this happens.

**Comment by ssoftwares** [comment]
![image](https://user-images.githubusercontent.com/71498747/96147120-a2d46580-0f24-11eb-9fc7-41dd3022e3be.png)
![image](https://user-images.githubusercontent.com/71498747/96147160-ab2ca080-0f24-11eb-8bb4-3e3169d701da.png)
![image](https://user-images.githubusercontent.com/71498747/96147208-b7b0f900-0f24-11eb-9dd7-66eb026ec7b3.png)


Log below: 
 Process: com.ssoftwares.dify, PID: 30915
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ssoftwares.dify/com.ssoftwares.dify.activity.TestActivity}: android.view.InflateException: Binary XML file line #10 in com.ssoftwares.dify:layout/activity_test: Binary XML file line #10 in com.ssoftwares.dify:layout/activity_test: Error inflating class com.github.anastr.rulerview.RulerView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.InflateException: Binary XML file line #10 in com.ssoftwares.dify:layout/activity_test: Binary XML file line #10 in com.ssoftwares.dify:layout/activity_test: Error inflating class com.github.anastr.rulerview.RulerView
     Caused by: android.view.InflateException: Binary XML file line #10 in com.ssoftwares.dify:layout/activity_test: Error inflating class com.github.anastr.rulerview.RulerView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.ssoftwares.dify.activity.TestActivity.onCreate(TestActivity.java:14)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at com.github.anastr.rulerview.RulerView.<init>(Unknown Source:2)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:854) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161) 
        at com.ssoftwares.dify.activity.TestActivity.onCreate(TestActivity.java:14) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2020-10-15 20:25:33.434 30915-30915/com.ssoftwares.dify E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.ssoftwares.dify-lBR-Hh4r_1PEr04Ymzxy-g==/base.apk"],nativeLibraryDirectories=[/data/app/com.ssoftwares.dify-lBR-Hh4r_1PEr04Ymzxy-g==/lib/x86, /data/app/com.ssoftwares.dify-lBR-Hh4r_1PEr04Ymzxy-g==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 29 more

**Comment by anastr** [comment]
This looks like missed Kotlin.

Please add Kotlin to your project and try again

**Comment by ssoftwares** [comment]
@anastr Thanks dude, it worked, i was not knowing that to work on kotlin we have to add its support in gradle.
